commits: https://github.com/kidlj/site/commits/master/

permalink: /blog/:year-:month-:day-:title

# plugins:
  # - jekyll-paginate
  # - kramdown

# paginate: 10
# paginate_path: "blog/page/:num"

# GitHub Pages don't use plugins
# kramdown:
#   syntax_highlighter: coderay
#   syntax_highlighter_opts:
#     line_numbers: false
#   coderay_tab_width: 4

defaults:
- scope: 
    path: ""
    type: "posts"
  values:
    layout: "post"

- scope:
    path: ""
    type: "wiki"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "code"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "read"
  values:
    layout: "read"

collections:
  wiki:
    output: true
    permalink: /wiki/:name
  code:
    output: true
    permalink: /code/:name
  read:
    output: true
    permalink: /read/:name
