commits: https://github.com/kidlj/awei/commits/main

defaults:
- scope: 
    type: "blog"
  values:
    layout: "blog"
- scope:
    type: "wiki"
  values:
    layout: "wiki"

collections:
  blog:
    output: true
    permalink: /blog/:name
  wiki:
    output: true
    permalink: /wiki/:name