services:
  jekyll:
    image: ruby
    command: bash -c "gem install bundler jekyll && jekyll serve --watch --incremental --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    environment:
      JEKYLL_ENV: development
